/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    fontFamily: {
      sans: ['var(--font-montserrat)', 'sans-serif'],
      serif: ['var(--font-montserrat)', 'sans-serif'],
    },
    extend: {
      colors: {
        primary: {
          50: '#e6f0f3',
          100: '#c2d9e3',
          200: '#9ac1d1',
          300: '#72a8bf',
          400: '#4a8fad',
          500: '#0b2f40',
          600: '#0a293a',
          700: '#082330',
          800: '#061c26',
          900: '#04151c',
          DEFAULT: '#0b2f40',
        },
        secondary: {
          50: '#e8eef0',
          100: '#c5d5dd',
          200: '#9eb9c7',
          300: '#779db1',
          400: '#50819b',
          500: '#184250',
          600: '#163d48',
          700: '#123540',
          800: '#0e2c38',
          900: '#0a2330',
          DEFAULT: '#184250',
        },
        accent: {
          50: '#f0ebfc',
          100: '#d9d0f6',
          200: '#c0b2ef',
          300: '#a794e8',
          400: '#8e76e1',
          500: '#7e49de',
          600: '#6a41c7',
          700: '#5639af',
          800: '#423198',
          900: '#2e2a80',
          DEFAULT: '#7e49de',
        },
        accentDark: {
          50: '#ece8f4',
          100: '#d0c9e4',
          200: '#b1a8d2',
          300: '#9287c0',
          400: '#7366ae',
          500: '#412576',
          600: '#392169',
          700: '#311c5c',
          800: '#29174f',
          900: '#211242',
          DEFAULT: '#412576',
        },
        brand: {
          blue: '#0b2f40',
          'blue-light': '#184250',
          'blue-dark': '#061c26',
          purple: '#7e49de',
          'purple-light': '#9e79ef',
          'purple-dark': '#412576',
        },
        dark: {
          bg: '#060d12',
          'bg-secondary': '#0b2f40',
          'bg-tertiary': '#0f3642',
          card: '#0b2a38',
          border: '#1a3d4d',
          text: '#f1f5f9',
          'text-secondary': '#94a3b8',
          'text-muted': '#64748b',
        },
        light: {
          bg: '#f8fafc',
          'bg-secondary': '#f1f5f9',
          'bg-tertiary': '#e2e8f0',
          card: '#ffffff',
          border: '#e2e8f0',
          text: '#0f172a',
          'text-secondary': '#475569',
          'text-muted': '#94a3b8',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
        'elegant': '0 0 40px -10px rgba(11, 47, 64, 0.15)',
        'glow': '0 0 20px rgba(126, 73, 222, 0.3)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-blue-purple': 'linear-gradient(135deg, #0b2f40 0%, #184250 25%, #7e49de 50%, #9e79ef 75%, #412576 100%)',
        'gradient-primary': 'linear-gradient(135deg, #0b2f40 0%, #184250 100%)',
        'gradient-accent': 'linear-gradient(135deg, #7e49de 0%, #412576 100%)',
        'gradient-dark': 'linear-gradient(to bottom right, #060d12, #0b2f40)',
        'gradient-card': 'linear-gradient(145deg, rgba(11, 47, 64, 0.1) 0%, rgba(126, 73, 222, 0.1) 100%)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'fade-in': {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        'fade-in-up': {
          from: { opacity: 0, transform: 'translateY(20px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        'fade-in-down': {
          from: { opacity: 0, transform: 'translateY(-20px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        'fade-in-left': {
          from: { opacity: 0, transform: 'translateX(-20px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'fade-in-right': {
          from: { opacity: 0, transform: 'translateX(20px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        'slide-in-from-top': {
          from: { transform: 'translateY(-100%)' },
          to: { transform: 'translateY(0)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.7 },
        },
        'gradient': {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'wiggle': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'shimmer': {
          from: { backgroundPosition: '200% 0' },
          to: { backgroundPosition: '-200% 0' },
        },
        'blob': {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        'glow': {
          '0%, 100%': { opacity: 0.5 },
          '50%': { opacity: 1 },
        },
        'scale-in': {
          from: { opacity: 0, transform: 'scale(0.9)' },
          to: { opacity: 1, transform: 'scale(1)' },
        },
        'rotate-in': {
          from: { opacity: 0, transform: 'rotate(-10deg) scale(0.9)' },
          to: { opacity: 1, transform: 'rotate(0) scale(1)' },
        },
        'orbit': {
          '0%': { transform: 'rotate(0deg) translateX(100px) rotate(0deg)' },
          '100%': { transform: 'rotate(360deg) translateX(100px) rotate(-360deg)' },
        },
        'float-3d': {
          '0%, 100%': { transform: 'translateY(0) rotateX(0deg) rotateY(0deg)' },
          '25%': { transform: 'translateY(-10px) rotateX(5deg) rotateY(5deg)' },
          '50%': { transform: 'translateY(0) rotateX(0deg) rotateY(0deg)' },
          '75%': { transform: 'translateY(10px) rotateX(-5deg) rotateY(-5deg)' },
        },
        'wave': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'marquee': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'pulse-border': {
          '0%, 100%': { borderColor: 'rgba(11, 47, 64, 0.3)' },
          '50%': { borderColor: 'rgba(11, 47, 64, 0.8)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-in-up': 'fade-in-up 0.5s ease-out',
        'fade-in-down': 'fade-in-down 0.5s ease-out',
        'fade-in-left': 'fade-in-left 0.5s ease-out',
        'fade-in-right': 'fade-in-right 0.5s ease-out',
        'slide-in': 'slide-in-from-top 0.3s ease-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse-slow 2s ease-in-out infinite',
        'gradient': 'gradient 3s ease infinite',
        'bounce-slow': 'bounce-slow 2s ease-in-out infinite',
        'spin-slow': 'spin-slow 8s linear infinite',
        'wiggle': 'wiggle 1s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'blob': 'blob 7s infinite',
        'glow': 'glow 2s ease-in-out infinite',
        'scale-in': 'scale-in 0.5s ease-out',
        'rotate-in': 'rotate-in 0.5s ease-out',
        'orbit': 'orbit 10s linear infinite',
        'float-3d': 'float-3d 6s ease-in-out infinite',
        'wave': 'wave 2s linear infinite',
        'marquee': 'marquee 25s linear infinite',
        'pulse-border': 'pulse-border 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
