# Generated by Django 6.0.3 on 2026-03-22 22:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_user_organization_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.organization')),
            ],
            options={
                'db_table': 'automation_notification_templates',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('email', 'Email'), ('report', 'Report Generation'), ('sync', 'Data Sync'), ('backup', 'Backup'), ('cleanup', 'Cleanup'), ('notification', 'Notification'), ('payroll', 'Payroll Processing'), ('invoice', 'Invoice Generation'), ('reminder', 'Reminder'), ('custom', 'Custom')], max_length=50)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_automated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='core.organization')),
            ],
            options={
                'db_table': 'automation_scheduled_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(max_length=50)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('event', 'Event Based'), ('condition', 'Condition Based')], default='manual', max_length=50)),
                ('trigger_config', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_automated', models.BooleanField(default=True)),
                ('run_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_workflows', to='core.organization')),
            ],
            options={
                'db_table': 'automation_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('email', 'Send Email'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('notify', 'Send Notification'), ('webhook', 'Call Webhook'), ('approve', 'Request Approval'), ('assign', 'Assign Task')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_automated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='automation.workflow')),
            ],
            options={
                'db_table': 'automation_actions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('trigger_data', models.JSONField(default=dict)),
                ('execution_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflow')),
            ],
            options={
                'db_table': 'automation_workflow_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationSetting',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('module', models.CharField(max_length=50)),
                ('setting_name', models.CharField(max_length=100)),
                ('setting_key', models.CharField(max_length=100)),
                ('value', models.JSONField(default=dict)),
                ('is_automated', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('schedule', models.JSONField(default=dict)),
                ('notification', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='core.organization')),
            ],
            options={
                'db_table': 'automation_settings',
                'unique_together': {('organization', 'module', 'setting_key')},
            },
        ),
    ]
