# Generated by Django 4.2.29 on 2026-03-24 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.workflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_workflows', to='core.organization'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='core.organization'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.organization'),
        ),
        migrations.AddField(
            model_name='automationsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_settings', to='core.organization'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_actions', to='automation.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='automationsetting',
            unique_together={('organization', 'module', 'setting_key')},
        ),
    ]
