# Generated by Django 6.0.3 on 2026-03-20 13:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('report', 'Report'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('folder', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('uploaded_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
