# Generated by Django 6.0.3 on 2026-03-20 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('payroll_number', models.CharField(db_index=True, max_length=50)),
                ('pay_period', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_employees', models.IntegerField(default=0)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_by', models.UUIDField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payrolls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('employee_id', models.UUIDField(db_index=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_aid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payroll')),
            ],
            options={
                'db_table': 'payslips',
                'ordering': ['-created_at'],
            },
        ),
    ]
