# Generated by Django 6.0.3 on 2026-03-22 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='US', max_length=10)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription', models.CharField(default='starter', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('modules', models.JSONField(default=list)),
                ('max_users', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR Manager'), ('finance', 'Finance Manager'), ('manager', 'Manager'), ('employee', 'Employee'), ('ordinary', 'Ordinary User')], default='employee', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=36, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('telecommunications', 'Telecommunications'), ('realestate', 'Real Estate'), ('legal', 'Legal'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=50, null=True)),
                ('subscription', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('country', models.CharField(default='US', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('modules', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_on_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
