# Generated by Django 6.0.3 on 2026-03-20 12:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='ZA', max_length=3)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('telecommunications', 'Telecommunications'), ('realestate', 'Real Estate'), ('legal', 'Legal'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=30)),
                ('subscription', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR Manager'), ('finance', 'Finance Manager'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('employee', 'Employee'), ('ordinary', 'Ordinary User')], default='employee', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('telecommunications', 'Telecommunications'), ('realestate', 'Real Estate'), ('legal', 'Legal'), ('consulting', 'Consulting'), ('other', 'Other')], default='other', max_length=30)),
                ('subscription', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('BW', 'Botswana'), ('MW', 'Malawi'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('US', 'United States'), ('GB', 'United Kingdom'), ('AU', 'Australia')], default='ZA', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_on_trial', models.BooleanField(default=False)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
