# Generated by Django 6.0.3 on 2026-03-22 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='extra_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='extra_users_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_users_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_groups',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='organization',
            name='max_users',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('finance', 'Finance'), ('construction', 'Construction'), ('hospitality', 'Hospitality'), ('transportation', 'Transportation'), ('agriculture', 'Agriculture'), ('mining', 'Mining'), ('telecommunications', 'Telecommunications'), ('realestate', 'Real Estate'), ('legal', 'Legal'), ('consulting', 'Consulting'), ('marketing', 'Marketing'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Organization Admin'), ('hr', 'HR Manager'), ('finance', 'Finance Manager'), ('accounting', 'Accountant'), ('manager', 'Manager'), ('employee', 'Employee'), ('ordinary', 'Ordinary User')], default='employee', max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=36)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(default='general', max_length=50)),
                ('permissions', models.JSONField(default=dict)),
                ('modules_access', models.JSONField(default=list)),
                ('members', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.organization')),
            ],
            options={
                'db_table': 'core_user_groups',
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
